Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/GuardClause:
  Enabled: false